/**
 * Social-card generation is best-effort.
 *
 * `next/og` renders the real card, but it cannot initialise when the project
 * path contains a space (a known @vercel/og limitation, mostly hit on local
 * Windows checkouts). Rather than failing the build or serving a 500, the
 * image routes fall back to a static PNG generated by scripts/generate-icons.mjs.
 */

/**
 * Buffers an ImageResponse so failures surface where they can be caught.
 *
 * `new ImageResponse(...)` returns a streaming response: if font loading or
 * rasterisation blows up, it does so mid-pipe, long after the try/catch around
 * the constructor has been left behind ("failed to pipe response"). Draining
 * the body here moves that failure back inside the caller's try/catch, which is
 * the only way the fallback can actually run.
 */
export async function bufferImageResponse(response: Response): Promise<Response> {
  const body = await response.arrayBuffer();
  return new Response(body, {
    status: 200,
    headers: {
      'Content-Type': 'image/png',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400, stale-while-revalidate=604800',
    },
  });
}

export function ogFallbackResponse(): Response {
  // Relative Location on purpose: works on any origin (localhost, preview,
  // production) without depending on NEXT_PUBLIC_APP_URL being correct.
  return new Response(null, {
    status: 307,
    headers: { Location: '/og-fallback.png', 'Cache-Control': 'public, max-age=300' },
  });
}

export function logOgFailure(scope: string, error: unknown): void {
  const message = error instanceof Error ? error.message : 'unknown error';
  console.warn(`[aura:og:${scope}] falling back to static card — ${message}`);
}
